import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'CalculatorModel.freezed.dart';

@freezed
class CalculatorModel with _$CalculatorModel {
  const factory CalculatorModel({required double result}) = _CalculatorModel;
}

// class CalculatorModel extends Equatable {
//   final double result;

//   const CalculatorModel({this.result = 0});

//   @override
//   List<Object> get props => [result];
// }
